application: resumenadzrin
version: 1
runtime: php55
api_version: 1

handlers:
- url: /assets
	static_dir: img
- url: /assets
	static_dir: js
- url: /assets
	ststic_dir: css
- url: /.*
  script: index.php
