application: resumenadzrin
version: 1
runtime: php55
api_version: 1

handlers:
- url: /assets
	static_dir: assets/img
- url: /assets
	static_dir: assets/js
- url: /assets
	ststic_dir: assets/css
- url: /.*
  script: index.php
