application: resumenadzrin
version: 1
runtime: php55
api_version: 1

handlers:
- url: /assets
  static_dir: assets/img

- url: /assets
  static_dir: assets/js

- url: /assets
  static_dir: assets/css

- url: /assets
  static_dir: assets/font

- url: /assets
  static_dir: assets/fonts

- url: /.*
  script: index.php
